working-directory = inherit
custom-shader-animation = true
clipboard-read = allow
clipboard-write = allow
window-theme = system
window-padding-x = 25
window-padding-y = 25
window-padding-balance = true
cursor-style-blink = true
font-size = 10
font-thicken = true
mouse-hide-while-typing = true
focus-follows-mouse = true
gtk-single-instance = false
