working-directory = inherit
custom-shader-animation = true
clipboard-read = allow
clipboard-write = allow
window-theme = system
window-padding-balance = true
window-padding-y=25
window-padding-x=25
window-padding-color=extend
theme = catppuccin-mocha
cursor-style-blink = true
font-size = 16
font-thicken = true
font-family = "scientifica"
mouse-hide-while-typing = true
focus-follows-mouse = false
gtk-single-instance = false
macos-option-as-alt = left
