theme = "catppuccin_mocha"
# theme = "base16_terminal"

[editor]
auto-completion = true
auto-format = true
color-modes = true
completion-replace = true
completion-trigger-len = 2
line-number = "relative"
mouse = true
popup-border = "all"
true-color = true

[editor.auto-save]
focus-lost = true
[editor.auto-save.after-delay]
enable = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
git-exclude = false
git-global = true
git-ignore = false
hidden = true
max-depth = 4
parents = false

[editor.indent-guides]
render = true

[editor.lsp]
auto-signature-help = true
display-inlay-hints = true
display-messages = true
enable = true
snippets = true

[editor.smart-tab]
enable = true
supersede-menu = false

[editor.soft-wrap]
enable = true
max-wrap = 80

[keys]
[keys.insert]
S-tab = "move_parent_node_start"

[keys.normal]
S-tab = "move_parent_node_start"
tab = "move_parent_node_end"

[keys.normal.space]
space = "workspace_symbol_picker"

[keys.select]
S-tab = "extend_parent_node_start"
tab = "extend_parent_node_end"
